### ISSUE TITLE
关于在1.10以上版本的使用

### ISSUE THREAD

**Issue by BryanSer** [Jerrylum/EffectEdit#2]
看的出来数据包处理使用的是https://github.com/DarkBlade12/ParticleEffect 
在这里 数据包初始化时获取版本采用的是version = Integer.parseInt(Character.toString(ReflectionUtils.PackageType.getServerVersion().charAt(3)));
所以在1.10及以上时获取的版本号为1
只需要将这部分修改为
String version_s = Bukkit.getServer().getClass().getPackage().getName().split("\\.")[3];
version_s = version_s.split("_")[1];
version = Integer.parseInt(version_s);
就可以解决问题

**Comment by Jerrylum** [comment]
紧急修复, 请各位测试一下
使用eclipse 编译应该可以

错误根据:
```log
[21:12:47] [Thread-35/WARN]: java.lang.NullPointerException
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.effect.EffectUtil$ParticlePacket.sendToWithKCauldron(EffectUtil.java:123)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.effect.EffectUtil$ParticlePacket.sendTo(EffectUtil.java:111)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.effect.EffectUtil$ParticlePacket.sendTo(EffectUtil.java:201)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.Util.EffectSession.effect(EffectSession.java:21)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.Util.EffectSession.makeCylinder(EffectSession.java:63)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.lib.LuaEffect$Circle.invoke(LuaEffect.java:94)
[21:12:47] [Thread-35/WARN]: 	at org.luaj.vm2.LuaClosure.execute(LuaClosure.java:367)
[21:12:47] [Thread-35/WARN]: 	at org.luaj.vm2.LuaClosure.call(LuaClosure.java:133)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.Util.EffectLua.run(EffectLua.java:76)
[21:12:47] [Thread-35/WARN]: 	at io.Jerry.EffectEdit.Commands.EffectEditCommand$1.run(EffectEditCommand.java:102)
```
估计原因: 插件错误判断伺服器版本, 导致显示粒子出现错误

@BryanSer

**Comment by BryanSer** [comment]
可以close了

**Comment by Jerrylum** [comment]
尚未測試

**Comment by BryanSer** [comment]
啊 我确实是漏打了一个\
